export default {
  DEFAULT_CELL_SIZE: 40,

  DEFAULT_COLS: 20,
  DEFAULT_ROWS: 20,

  DEFAULT_WIDTH: 20 * 40 + 20,
  DEFAULT_HEIGHT: 20 * 40 + 20,

  //   DEFAULT_WIDTH: DEFAULT_COLS * DEFAULT_CELL_SIZE + 20,
  //   DEFAULT_HEIGHT: DEFAULT_ROWS * DEFAULT_CELL_SIZE + 20,
};
